### ISSUE TITLE
MY F1 is low, what happen to me?

### ISSUE THREAD

**Issue by hquzhuguofeng** [adamluo1995/Bert4CoQA#1]
Dear adamluo1995:
        i am follow your code with the coqa dataset,but my score is low.
And my parameters is the same as yours.
- --bert_model bert-base-uncased
- --num_train_epochs 3.0
- --do_lower_case
- --max_seq_length 450
- --doc_stride 150
- --max_query_length 75  
and you can get f1 75%,  and i didnot change your code. did i use wrong version of bert-pretrain-model ? can you help me?
{
  "children_stories": {
    "em": 15.7,
    "f1": 19.9,
    "turns": 1425
  },
  "literature": {
    "em": 15.4,
    "f1": 18.3,
    "turns": 1630
  },
  "mid-high_school": {
    "em": 16.1,
    "f1": 18.8,
    "turns": 1653
  },
  "news": {
    "em": 15.7,
    "f1": 19.5,
    "turns": 1649
  },
  "wikipedia": {
    "em": 14.5,
    "f1": 18.4,
    "turns": 1626
  },
  "reddit": {
    "em": 0.0,
    "f1": 0.0,
    "turns": 0
  },
  "science": {
    "em": 0.0,
    "f1": 0.0,
    "turns": 0
  },
  "in_domain": {
    "em": 15.5,
    "f1": 19.0,
    "turns": 7983
  },
  "out_domain": {
    "em": 0.0,
    "f1": 0.0,
    "turns": 0
  },
  "overall": {
    "em": 15.5,
    "f1": 19.0,
    "turns": 7983
  }
}
above is my result.

**Comment by fairy-of-9** [comment]
hi @hquzhuguofeng 
I'm following this code.
I downloaded BERT model from [google-bert](https://github.com/google-research/bert)
and I tried 
`python run_coqa.py --bert_model bert-base-uncased --num_train_epochs 3.0 --do_lower_case --max_seq_length 450 --doc_stride 150 --max_query_length 75 --output_dir out --do_train --train_file coqa-train-v1.0.json`

but It didn't work.

It's my result.
```
Namespace(bert_model='bert-base-uncased', cuda_visiable='0', do_lower_case=True, do_predict=False, do_train=True, doc_stride=150, fp16=False, gradient_accumulation_steps=1, history_len=2, learning_rate=5e-05, local_rank=-1, logfile=None, logmode=None, loss_scale=0, max_answer_length=30, max_query_length=75, max_seq_length=450, n_best_size=20, no_cuda=False, no_tensorboard=False, null_score_diff_threshold=0.0, num_train_epochs=3.0, output_dir='out', overwrite_output_dir=False, predict_batch_size=128, predict_file=None, qa_tag=False, seed=42, server_ip='', server_port='', train_batch_size=32, train_file='coqa-train-v1.0.json', verbose_logging=False, warmup_proportion=0.1, wordrop_rate=0.0)
12/04/2019 13:09:25 - INFO - __main__ -   device: cpu n_gpu: 0, distributed training: False, 16-bits training: False
12/04/2019 13:09:26 - INFO - pytorch_pretrained_bert.file_utils -   https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt not found in cache, downloading to /tmp/tmpabqhm9c_
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 231508/231508 [00:00<00:00, 412420.91B/s]
12/04/2019 13:09:27 - INFO - pytorch_pretrained_bert.file_utils -   copying /tmp/tmpabqhm9c_ to cache at /home/fairy_of_9/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
12/04/2019 13:09:27 - INFO - pytorch_pretrained_bert.file_utils -   creating metadata file for /home/fairy_of_9/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
12/04/2019 13:09:27 - INFO - pytorch_pretrained_bert.file_utils -   removing temp file /tmp/tmpabqhm9c_
12/04/2019 13:09:27 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/fairy_of_9/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
12/04/2019 13:09:28 - INFO - pytorch_pretrained_bert.file_utils -   https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz not found in cache, downloading to /tmp/tmpuxcnkdbd
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 407873900/407873900 [04:38<00:00, 1464785.36B/s]
12/04/2019 13:14:08 - INFO - pytorch_pretrained_bert.file_utils -   copying /tmp/tmpuxcnkdbd to cache at /home/fairy_of_9/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
12/04/2019 13:14:08 - INFO - pytorch_pretrained_bert.file_utils -   creating metadata file for /home/fairy_of_9/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
12/04/2019 13:14:08 - INFO - pytorch_pretrained_bert.file_utils -   removing temp file /tmp/tmpuxcnkdbd
12/04/2019 13:14:08 - INFO - pytorch_pretrained_bert.modeling -   loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /home/fairy_of_9/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
12/04/2019 13:14:08 - INFO - pytorch_pretrained_bert.modeling -   extracting archive file /home/fairy_of_9/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /tmp/tmpnj310xxg
12/04/2019 13:14:14 - INFO - pytorch_pretrained_bert.modeling -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

Traceback (most recent call last):
  File "run_coqa.py", line 675, in <module>
    main()
  File "run_coqa.py", line 319, in main
    mask_p=args.wordrop_rate)
  File "/home/fairy_of_9/anaconda3/envs/bert/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 600, in from_pretrained
    model = cls(config, *inputs, **kwargs)
  File "/home/fairy_of_9/Bert4CoQA/modeling.py", line 24, in __init__
    keep_multihead_output=keep_multihead_output,
TypeError: __init__() got an unexpected keyword argument 'output_attentions'

```

**Comment by adamluo1995** [comment]
@hquzhuguofeng 
Maybe you load the raw model without fine-tuning to do evaluation. You might have already fine-tuned, but didn't load this fine-tuned model when doing evaluation.

**Comment by adamluo1995** [comment]
@fairy-of-9 
It caused by the mismatch of pytorch-pretrained-bert. Huggingface like to change its transformers code, but I didn't recognized it at first time. It's hard to download the same version as me. I will change the code recently, and package all dependencies to prevent this mismatch.

**Comment by fairy-of-9** [comment]
@adamluo1995 
Thanks a lot !!

**Comment by naseeihity** [comment]
Hi @adamluo1995, I just run the code using your parameters(directly run run.sh), but got F1 only 46, is there any other thing need to be modified?

**Comment by adamluo1995** [comment]
--do_lower_case should be set with bert-base-uncased. I have updated code and you can try it again.

**Comment by adamluo1995** [comment]
@naseeihity --do_lower_case should be set with bert-base-uncased. I have updated code and you can try it again.
